- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: true
  become: true

- name: Download and install the Public Signing Key and Save the repository definition
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/9.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-9.x.list
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Instasll filebeat
  ansible.builtin.apt:
     name: filebeat
     state: present
     update_cache: true

- name: Config file filebeat.yml
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'

- name: Reload systemcd daemon
  ansible.builtin.systemd:
    daemon_reload: yes


- name: Enable filebeat service
  ansible.builtin.systemd:
    name: filebeat.service
    enabled: yes

- name: Start filebeat service
  ansible.builtin.systemd:
    name: filebeat.service
    state: started

- name: restart filebeat service
  ansible.builtin.systemd:
    name: filebeat.service
    state: restarted

- name: Run filebeat test output
  shell: filebeat test output
  register: test_output
  ignore_errors: true

- name: Show result
  debug:
    var: test_output.stdout_lines
