- name: update system
  become: true
  apt:
    update_cache: true

- name: Check if Elastic APT source list file exists
  stat:
    path: /etc/apt/sources.list.d/elastic-9.x.list
  register: elastic_repo_file

- name: Download and install the Public Signing Key
  ansible.builtin.shell: | 
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  update_cache: true
  become: true
  when: not elastic_repo_file.stat.exists

- name: Ensure apt-transport-https is installed
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: not elastic_repo_file.stat.exists

- name: Add Elastic APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main"
    filename: elastic-9.x
  when: not elastic_repo_file.stat.exists

- name: Instasll filebeat
  ansible.builtin.apt:
    - name: filebeat
    - state: present
    - update_cache: true

- name: Config file filebeat.yml
  ansible.builtin.template:
    - src: filebeat.yml.j2
    - dest: /etc/filebeat/filebeat.yml
    - owner: root
    - group: root
    - mode: '0644'

- name: Reload systemcd daemon
  ansible.builtin.systemd:
    daemon_reload: yes


- name: Enable filebeat service
  ansible.builtin.systemd:
    name: filebeat.service
    enabled: yes

- name: Start filebeat service
  ansible.builtin.systemd:
    name: filebeat.service
    state: started

- name: Run filebeat test output
  shell: filebeat test output
  register: test_output
  ignore_errors: true

- name: Show result
  debug:
    var: test_output.stdout_lines
