
- name: Cài đặt các package cần thiết
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
      - nginx
    update_cache: yes

- name: Tạo thư mục ứng dụng
  file:
    path: /opt/flask-app
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy Flask app lên server
  copy:
    src: ../../../../app/
    dest: /opt/flask-app/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Tạo virtualenv và cài requirements
  shell: |
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  args:
    chdir: /opt/flask-app/
    executable: /bin/bash

- name: Tạo systemd service cho Gunicorn
  copy:
    dest: /etc/systemd/system/flask-app.service
    content: |
      [Unit]
      Description=Gunicorn Flask App
      After=network.target

      [Service]
      User=www-data
      Group=www-data
      WorkingDirectory=/opt/flask-app
      EnvironmentFile=/opt/flask-app/.env
      ExecStart=/opt/flask-app/venv/bin/gunicorn --workers 3 --bind unix:/opt/flask-app/flask.sock app:app

      [Install]
      WantedBy=multi-user.target

- name: Reload và enable service
  shell: |
    systemctl daemon-reload
    systemctl enable flask-app
    systemctl restart flask-app

- name: Cấu hình Nginx reverse proxy
  copy:
    dest: /etc/nginx/sites-available/flask-app
    content: |
      server {
          listen 80;
          server_name 34.70.98.212;

          location / {
              include proxy_params;
              proxy_pass http://unix:/opt/flask-app/flask.sock;
          }
      }

- name: Enable Nginx config
  file:
    src: /etc/nginx/sites-available/flask-app
    dest: /etc/nginx/sites-enabled/flask-app
    state: link
    force: yes

- name: Xóa default site của Nginx nếu có
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

